package aws.lamda;

import java.util.HashMap;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

public class MyFirstLambdaWithAPIGatewaySample2 implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

	Gson gson = new GsonBuilder().setPrettyPrinting().create();

	@Override
	public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent input, Context context) {
		System.out.println("handleRequest is invoked...........");

		final LambdaLogger logger = context.getLogger();
		APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();

		logger.log("from logger -> handleRequest is invoked...........\n");
		logger.log("getAwsRequestId " + context.getAwsRequestId() + "\n");
		logger.log("getFunctionName " + context.getFunctionName() + "\n");
		logger.log("getFunctionVersion " + context.getFunctionVersion() + "\n");
		logger.log("getInvokedFunctionArn " + context.getInvokedFunctionArn() + "\n");
		logger.log("getLogGroupName " + context.getLogGroupName() + "\n");
		logger.log("getLogStreamName " + context.getLogStreamName() + "\n");
		logger.log("getAwsRequestId " + context.getAwsRequestId() + "\n");
		logger.log("getMemoryLimitInMB " + context.getMemoryLimitInMB() + "\n");
		logger.log("getRemainingTimeInMillis " + context.getRemainingTimeInMillis() + "\n");

		logger.log("getClientContext " + gson.toJson(context.getClientContext()) + "\n");
		logger.log("context " + gson.toJson(context) + "\n");
		logger.log("getIdentity " + gson.toJson(context.getIdentity()) + "\n");

		logger.log("incoming request is " + gson.toJson(input) + "\n");
		logger.log("dumping request " + input + "\n");
		logger.log("request body "+input.getBody());
		logger.log("request headers "+input.getHeaders());
		
		logger.log("processing incoming request.....version-5........" + "\n");
		response.setStatusCode(200);
		HashMap<String, String> headers = new HashMap<String, String>();
		headers.put("Content-Type", "text/html");
		response.setHeaders(headers);
		response.setBody("<!DOCTYPE html><html><head><title>AWS Lambda sample</title></head><body>"
				+ "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" + "</body></html>");

		logger.log("logging response.............." + "\n");

		logger.log("response is " + gson.toJson(response) + "\n");

		return response;
	}

}
