spring: 
   application:
       name: cognito-integration
   security:
    session:
      create-session: never
      #below configuraton does following works
      #Automatically extract and validate the JWT from the Authorization: Bearer ... header
      #Decode it using the JWKS URI derived from the issuer
    oauth2:
      resourceserver:
         jwt:
           issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_CCHScpCEi